name: PHPStan

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
      - 'data'
      - 'MailScanner_perl_scripts'
      - 'tools/MailScanner_config'
      - 'tools/sudo'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'data'
      - 'MailScanner_perl_scripts'
      - 'tools/MailScanner_config'
      - 'tools/sudo'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpstan:
    name: "PHP: 8.0 | PHPStan"

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpstan

      # Install dependencies and handle caching in one go.
      # Dependencies need to be installed to make sure the PHPUnit classes are recognized.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Run PHPStan
        run: phpstan analyse --configuration=phpstan.neon.dist --error-format=github
